### ISSUE TITLE
The Dogs Nearby Appears Twice

### ISSUE THREAD

**Issue by evaxliu** [evaliu2002/PetMyDog#60]
**Describe the bug**
When a user is on the find-dogs page of PMD, the user sees duplicate dogs displaying.

**To Reproduce**
1. Go to find dogs page.

**Expected behavior**
We expect the dogs to be displayed only once.

**Screenshots**
<img width="283" alt="image" src="https://user-images.githubusercontent.com/69877857/169959323-fbe32d93-8370-45fb-81fe-9b6aa8cb2a51.png">

**Desktop (please complete the following information):**
 - OS: Macbook Monterey 12.3.1 (21E258)
 - Browser: Chrome Version Version 101.0.4951.64 (Official Build) (x86_64)

**Comment by PROTONlwx** [comment]
Solved
